apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  template:
    metadata:
      labels:
        app: votingapp
        component: vote
    spec:  
      containers:
      - name: vote
        image: tekdemo.azurecr.io/vote:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
